/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TrackAppointmentRouteImport } from './routes/track-appointment'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as MaterialSlugRouteImport } from './routes/material.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminSignupRouteImport } from './routes/admin.signup'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AccountAccountIdRouteImport } from './routes/account.$accountId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AccountAccountIdTrackOrderRouteImport } from './routes/account.$accountId.track-order'
import { Route as AccountAccountIdRefundsRouteImport } from './routes/account.$accountId.refunds'
import { Route as AccountAccountIdProfileRouteImport } from './routes/account.$accountId.profile'
import { Route as AccountAccountIdOrdersRouteImport } from './routes/account.$accountId.orders'
import { Route as AccountAccountIdCheckoutRouteImport } from './routes/account.$accountId.checkout'
import { Route as AccountAccountIdCartRouteImport } from './routes/account.$accountId.cart'
import { Route as AccountAccountIdCancelledRouteImport } from './routes/account.$accountId.cancelled'
import { Route as AccountAccountIdAddressesRouteImport } from './routes/account.$accountId.addresses'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as AuthenticatedAdminWarrantyClaimsRouteImport } from './routes/_authenticated/admin.warranty-claims'
import { Route as AuthenticatedAdminWarrantyCertificateRouteImport } from './routes/_authenticated/admin.warranty-certificate'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin.offers'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminMaterialsRouteImport } from './routes/_authenticated/admin.materials'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCreateAdminRouteImport } from './routes/_authenticated/admin.create-admin'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCollectionsRouteImport } from './routes/_authenticated/admin.collections'
import { Route as AuthenticatedAdminCmsRouteImport } from './routes/_authenticated/admin.cms'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAppointmentRoute = TrackAppointmentRouteImport.update({
  id: '/track-appointment',
  path: '/track-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialSlugRoute = MaterialSlugRouteImport.update({
  id: '/material/$slug',
  path: '/material/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountIdRoute = AccountAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AccountRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountAccountIdTrackOrderRoute =
  AccountAccountIdTrackOrderRouteImport.update({
    id: '/track-order',
    path: '/track-order',
    getParentRoute: () => AccountAccountIdRoute,
  } as any)
const AccountAccountIdRefundsRoute = AccountAccountIdRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AccountAccountIdRoute,
} as any)
const AccountAccountIdProfileRoute = AccountAccountIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountAccountIdRoute,
} as any)
const AccountAccountIdOrdersRoute = AccountAccountIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountAccountIdRoute,
} as any)
const AccountAccountIdCheckoutRoute =
  AccountAccountIdCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AccountAccountIdRoute,
  } as any)
const AccountAccountIdCartRoute = AccountAccountIdCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AccountAccountIdRoute,
} as any)
const AccountAccountIdCancelledRoute =
  AccountAccountIdCancelledRouteImport.update({
    id: '/cancelled',
    path: '/cancelled',
    getParentRoute: () => AccountAccountIdRoute,
  } as any)
const AccountAccountIdAddressesRoute =
  AccountAccountIdAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AccountAccountIdRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWarrantyClaimsRoute =
  AuthenticatedAdminWarrantyClaimsRouteImport.update({
    id: '/warranty-claims',
    path: '/warranty-claims',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWarrantyCertificateRoute =
  AuthenticatedAdminWarrantyCertificateRouteImport.update({
    id: '/warranty-certificate',
    path: '/warranty-certificate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMaterialsRoute =
  AuthenticatedAdminMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCreateAdminRoute =
  AuthenticatedAdminCreateAdminRouteImport.update({
    id: '/create-admin',
    path: '/create-admin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCollectionsRoute =
  AuthenticatedAdminCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsRoute = AuthenticatedAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/appointment': typeof AppointmentRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-appointment': typeof TrackAppointmentRoute
  '/warranty': typeof WarrantyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/account/$accountId': typeof AccountAccountIdRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/category/$slug': typeof CategorySlugRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/create-admin': typeof AuthenticatedAdminCreateAdminRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/warranty-certificate': typeof AuthenticatedAdminWarrantyCertificateRoute
  '/admin/warranty-claims': typeof AuthenticatedAdminWarrantyClaimsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/account/$accountId/addresses': typeof AccountAccountIdAddressesRoute
  '/account/$accountId/cancelled': typeof AccountAccountIdCancelledRoute
  '/account/$accountId/cart': typeof AccountAccountIdCartRoute
  '/account/$accountId/checkout': typeof AccountAccountIdCheckoutRoute
  '/account/$accountId/orders': typeof AccountAccountIdOrdersRoute
  '/account/$accountId/profile': typeof AccountAccountIdProfileRoute
  '/account/$accountId/refunds': typeof AccountAccountIdRefundsRoute
  '/account/$accountId/track-order': typeof AccountAccountIdTrackOrderRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-appointment': typeof TrackAppointmentRoute
  '/warranty': typeof WarrantyRoute
  '/account/$accountId': typeof AccountAccountIdRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/category/$slug': typeof CategorySlugRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/create-admin': typeof AuthenticatedAdminCreateAdminRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/warranty-certificate': typeof AuthenticatedAdminWarrantyCertificateRoute
  '/admin/warranty-claims': typeof AuthenticatedAdminWarrantyClaimsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/account/$accountId/addresses': typeof AccountAccountIdAddressesRoute
  '/account/$accountId/cancelled': typeof AccountAccountIdCancelledRoute
  '/account/$accountId/cart': typeof AccountAccountIdCartRoute
  '/account/$accountId/checkout': typeof AccountAccountIdCheckoutRoute
  '/account/$accountId/orders': typeof AccountAccountIdOrdersRoute
  '/account/$accountId/profile': typeof AccountAccountIdProfileRoute
  '/account/$accountId/refunds': typeof AccountAccountIdRefundsRoute
  '/account/$accountId/track-order': typeof AccountAccountIdTrackOrderRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/appointment': typeof AppointmentRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-appointment': typeof TrackAppointmentRoute
  '/warranty': typeof WarrantyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/account/$accountId': typeof AccountAccountIdRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/category/$slug': typeof CategorySlugRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/_authenticated/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/create-admin': typeof AuthenticatedAdminCreateAdminRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/warranty-certificate': typeof AuthenticatedAdminWarrantyCertificateRoute
  '/_authenticated/admin/warranty-claims': typeof AuthenticatedAdminWarrantyClaimsRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/account/$accountId/addresses': typeof AccountAccountIdAddressesRoute
  '/account/$accountId/cancelled': typeof AccountAccountIdCancelledRoute
  '/account/$accountId/cart': typeof AccountAccountIdCartRoute
  '/account/$accountId/checkout': typeof AccountAccountIdCheckoutRoute
  '/account/$accountId/orders': typeof AccountAccountIdOrdersRoute
  '/account/$accountId/profile': typeof AccountAccountIdProfileRoute
  '/account/$accountId/refunds': typeof AccountAccountIdRefundsRoute
  '/account/$accountId/track-order': typeof AccountAccountIdTrackOrderRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/appointment'
    | '/auth'
    | '/book-appointment'
    | '/contact'
    | '/login'
    | '/new-arrivals'
    | '/privacy'
    | '/privacy-policy'
    | '/projects'
    | '/reset-password'
    | '/shipping'
    | '/signup'
    | '/terms'
    | '/terms-and-conditions'
    | '/track-appointment'
    | '/warranty'
    | '/admin'
    | '/account/$accountId'
    | '/admin/login'
    | '/admin/signup'
    | '/category/$slug'
    | '/material/$slug'
    | '/product/$slug'
    | '/projects/$slug'
    | '/account/'
    | '/admin/about'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/create-admin'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/materials'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/warranty-certificate'
    | '/admin/warranty-claims'
    | '/admin/webhooks'
    | '/account/$accountId/addresses'
    | '/account/$accountId/cancelled'
    | '/account/$accountId/cart'
    | '/account/$accountId/checkout'
    | '/account/$accountId/orders'
    | '/account/$accountId/profile'
    | '/account/$accountId/refunds'
    | '/account/$accountId/track-order'
    | '/api/public/razorpay-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/auth'
    | '/book-appointment'
    | '/contact'
    | '/login'
    | '/new-arrivals'
    | '/privacy'
    | '/privacy-policy'
    | '/projects'
    | '/reset-password'
    | '/shipping'
    | '/signup'
    | '/terms'
    | '/terms-and-conditions'
    | '/track-appointment'
    | '/warranty'
    | '/account/$accountId'
    | '/admin/login'
    | '/admin/signup'
    | '/category/$slug'
    | '/material/$slug'
    | '/product/$slug'
    | '/projects/$slug'
    | '/account'
    | '/admin/about'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/create-admin'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/materials'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/warranty-certificate'
    | '/admin/warranty-claims'
    | '/admin/webhooks'
    | '/account/$accountId/addresses'
    | '/account/$accountId/cancelled'
    | '/account/$accountId/cart'
    | '/account/$accountId/checkout'
    | '/account/$accountId/orders'
    | '/account/$accountId/profile'
    | '/account/$accountId/refunds'
    | '/account/$accountId/track-order'
    | '/api/public/razorpay-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/account'
    | '/appointment'
    | '/auth'
    | '/book-appointment'
    | '/contact'
    | '/login'
    | '/new-arrivals'
    | '/privacy'
    | '/privacy-policy'
    | '/projects'
    | '/reset-password'
    | '/shipping'
    | '/signup'
    | '/terms'
    | '/terms-and-conditions'
    | '/track-appointment'
    | '/warranty'
    | '/_authenticated/admin'
    | '/account/$accountId'
    | '/admin/login'
    | '/admin/signup'
    | '/category/$slug'
    | '/material/$slug'
    | '/product/$slug'
    | '/projects/$slug'
    | '/account/'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/cms'
    | '/_authenticated/admin/collections'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/create-admin'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/materials'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/warranty-certificate'
    | '/_authenticated/admin/warranty-claims'
    | '/_authenticated/admin/webhooks'
    | '/account/$accountId/addresses'
    | '/account/$accountId/cancelled'
    | '/account/$accountId/cart'
    | '/account/$accountId/checkout'
    | '/account/$accountId/orders'
    | '/account/$accountId/profile'
    | '/account/$accountId/refunds'
    | '/account/$accountId/track-order'
    | '/api/public/razorpay-webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AppointmentRoute: typeof AppointmentRoute
  AuthRoute: typeof AuthRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShippingRoute: typeof ShippingRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackAppointmentRoute: typeof TrackAppointmentRoute
  WarrantyRoute: typeof WarrantyRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignupRoute: typeof AdminSignupRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MaterialSlugRoute: typeof MaterialSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-appointment': {
      id: '/track-appointment'
      path: '/track-appointment'
      fullPath: '/track-appointment'
      preLoaderRoute: typeof TrackAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug': {
      id: '/material/$slug'
      path: '/material/$slug'
      fullPath: '/material/$slug'
      preLoaderRoute: typeof MaterialSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId': {
      id: '/account/$accountId'
      path: '/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof AccountAccountIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId/track-order': {
      id: '/account/$accountId/track-order'
      path: '/track-order'
      fullPath: '/account/$accountId/track-order'
      preLoaderRoute: typeof AccountAccountIdTrackOrderRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/account/$accountId/refunds': {
      id: '/account/$accountId/refunds'
      path: '/refunds'
      fullPath: '/account/$accountId/refunds'
      preLoaderRoute: typeof AccountAccountIdRefundsRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/account/$accountId/profile': {
      id: '/account/$accountId/profile'
      path: '/profile'
      fullPath: '/account/$accountId/profile'
      preLoaderRoute: typeof AccountAccountIdProfileRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/account/$accountId/orders': {
      id: '/account/$accountId/orders'
      path: '/orders'
      fullPath: '/account/$accountId/orders'
      preLoaderRoute: typeof AccountAccountIdOrdersRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/account/$accountId/checkout': {
      id: '/account/$accountId/checkout'
      path: '/checkout'
      fullPath: '/account/$accountId/checkout'
      preLoaderRoute: typeof AccountAccountIdCheckoutRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/account/$accountId/cart': {
      id: '/account/$accountId/cart'
      path: '/cart'
      fullPath: '/account/$accountId/cart'
      preLoaderRoute: typeof AccountAccountIdCartRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/account/$accountId/cancelled': {
      id: '/account/$accountId/cancelled'
      path: '/cancelled'
      fullPath: '/account/$accountId/cancelled'
      preLoaderRoute: typeof AccountAccountIdCancelledRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/account/$accountId/addresses': {
      id: '/account/$accountId/addresses'
      path: '/addresses'
      fullPath: '/account/$accountId/addresses'
      preLoaderRoute: typeof AccountAccountIdAddressesRouteImport
      parentRoute: typeof AccountAccountIdRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/warranty-claims': {
      id: '/_authenticated/admin/warranty-claims'
      path: '/warranty-claims'
      fullPath: '/admin/warranty-claims'
      preLoaderRoute: typeof AuthenticatedAdminWarrantyClaimsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/warranty-certificate': {
      id: '/_authenticated/admin/warranty-certificate'
      path: '/warranty-certificate'
      fullPath: '/admin/warranty-certificate'
      preLoaderRoute: typeof AuthenticatedAdminWarrantyCertificateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/materials': {
      id: '/_authenticated/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/create-admin': {
      id: '/_authenticated/admin/create-admin'
      path: '/create-admin'
      fullPath: '/admin/create-admin'
      preLoaderRoute: typeof AuthenticatedAdminCreateAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/collections': {
      id: '/_authenticated/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms': {
      id: '/_authenticated/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AuthenticatedAdminCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCmsRoute: typeof AuthenticatedAdminCmsRoute
  AuthenticatedAdminCollectionsRoute: typeof AuthenticatedAdminCollectionsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCreateAdminRoute: typeof AuthenticatedAdminCreateAdminRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminMaterialsRoute: typeof AuthenticatedAdminMaterialsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminWarrantyCertificateRoute: typeof AuthenticatedAdminWarrantyCertificateRoute
  AuthenticatedAdminWarrantyClaimsRoute: typeof AuthenticatedAdminWarrantyClaimsRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCmsRoute: AuthenticatedAdminCmsRoute,
  AuthenticatedAdminCollectionsRoute: AuthenticatedAdminCollectionsRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCreateAdminRoute: AuthenticatedAdminCreateAdminRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminMaterialsRoute: AuthenticatedAdminMaterialsRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminWarrantyCertificateRoute:
    AuthenticatedAdminWarrantyCertificateRoute,
  AuthenticatedAdminWarrantyClaimsRoute: AuthenticatedAdminWarrantyClaimsRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AccountAccountIdRouteChildren {
  AccountAccountIdAddressesRoute: typeof AccountAccountIdAddressesRoute
  AccountAccountIdCancelledRoute: typeof AccountAccountIdCancelledRoute
  AccountAccountIdCartRoute: typeof AccountAccountIdCartRoute
  AccountAccountIdCheckoutRoute: typeof AccountAccountIdCheckoutRoute
  AccountAccountIdOrdersRoute: typeof AccountAccountIdOrdersRoute
  AccountAccountIdProfileRoute: typeof AccountAccountIdProfileRoute
  AccountAccountIdRefundsRoute: typeof AccountAccountIdRefundsRoute
  AccountAccountIdTrackOrderRoute: typeof AccountAccountIdTrackOrderRoute
}

const AccountAccountIdRouteChildren: AccountAccountIdRouteChildren = {
  AccountAccountIdAddressesRoute: AccountAccountIdAddressesRoute,
  AccountAccountIdCancelledRoute: AccountAccountIdCancelledRoute,
  AccountAccountIdCartRoute: AccountAccountIdCartRoute,
  AccountAccountIdCheckoutRoute: AccountAccountIdCheckoutRoute,
  AccountAccountIdOrdersRoute: AccountAccountIdOrdersRoute,
  AccountAccountIdProfileRoute: AccountAccountIdProfileRoute,
  AccountAccountIdRefundsRoute: AccountAccountIdRefundsRoute,
  AccountAccountIdTrackOrderRoute: AccountAccountIdTrackOrderRoute,
}

const AccountAccountIdRouteWithChildren =
  AccountAccountIdRoute._addFileChildren(AccountAccountIdRouteChildren)

interface AccountRouteChildren {
  AccountAccountIdRoute: typeof AccountAccountIdRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAccountIdRoute: AccountAccountIdRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AppointmentRoute: AppointmentRoute,
  AuthRoute: AuthRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ShippingRoute: ShippingRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackAppointmentRoute: TrackAppointmentRoute,
  WarrantyRoute: WarrantyRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignupRoute: AdminSignupRoute,
  CategorySlugRoute: CategorySlugRoute,
  MaterialSlugRoute: MaterialSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
